# List of flirty truth questions
TRUTH_QUESTIONS = [
    "Who do you like? 😏",
    "Have you ever done something illegal? 🚔",
    "What was your worst rejection? 💔",
    "What's the most embarrassing thing you've done? 😳",
    "What's the grossest thing you've done? 🤢",
    "When were you last embarrassed? 😖",
    "What's your least favorite food? 🍽️",
    "Do you believe in ghosts? 👻",
    "Who's the last person you texted? 📱",
    "What's the biggest lie you've told? 🤥",
    "Who's your celebrity crush? 🌟",
    "What's your ideal date? ❤️",
    "When was your first kiss? 💏",
    "Who would you marry on the spot? 💍",
    "Do you believe in angels? 👼",
    
    # Existing flirty truth questions
    "What's your idea of a perfect romantic date? 💘",
    "What's the most attractive quality in a person? 😍",
    "Who was your first crush and why? 💕",
    "What's your biggest turn-off? 🙅‍♀️",
    "What's your biggest turn-on? 🔥",
    "Have you ever had a secret admirer? 💌",
    # ... (continue adding all previous truths)
    "Have you ever had a secret crush on someone? 💕",
    "What’s the most embarrassing thing that’s ever happened to you? 😳",
    "Have you ever told a lie that you regret? 🤥",
    "Who was your first love? ❤️",
    "What’s the most unusual thing you’ve ever eaten? 🍴",
    "Have you ever snooped through someone’s phone without them knowing? 📱",
    "What’s a fear you’ve never told anyone about? 😱",
    "Have you ever cheated in a relationship? 💔",
    "What’s the most childish thing you still enjoy? 🧸",
    "What’s a bad habit you wish you could break? 🚭",
    "Have you ever pretended to like something to impress someone? 🎭",
    "What’s the biggest lie you’ve ever told? 🕵️",
    "Who’s the most attractive person you know? 😍",
    "What’s a guilty pleasure you secretly enjoy? 🍫",
    "Have you ever cried during a movie? 🎥",
    "What’s the weirdest dream you’ve ever had? 🛌",
    "Have you ever stolen something? 🛍️",
    "What’s your most embarrassing childhood memory? 🧒",
    "If you could switch lives with anyone for a day, who would it be? 🔄",
    "What’s the most rebellious thing you’ve done? 😈",
    "Have you ever been caught lying? 😅",
    "What’s the most awkward date you’ve ever been on? 🥴",
    "Do you have a secret talent? 🎨",
    "Have you ever had a paranormal experience? 👻",
    "Who do you like more, your mom or dad? 👨‍👩‍👧",
    "What’s your biggest insecurity? 😔",
    "Have you ever fallen in love at first sight? 🌹",
    "What’s the weirdest rumor you’ve heard about yourself? 🤔",
    "Have you ever sent a text you immediately regretted? 📩",
    "What’s something you’ve done that you’ve never told anyone? 🤐",
    "Have you ever been in love with a friend? 💞",
    "What’s your biggest regret in life? 😢",
    "If you could erase one memory, what would it be? 🧠",
    "What’s the most overrated trend, in your opinion? 🌈",
    "Have you ever ghosted someone? 👻",
    "What’s a secret you’re keeping right now? 🔒",
    "Have you ever had a crush on a teacher? 🍎",
    "What’s the most embarrassing thing you’ve Googled? 🔍",
    "What’s a song that always makes you emotional? 🎵",
    "Have you ever faked being sick to skip school or work? 🛌",
    "Have you ever been jealous of a friend? 😒",
    "What’s the meanest thing you’ve ever done to someone? 🥺",
    "Do you believe in love at first sight? 💘",
    "What’s the weirdest thing you’ve ever done in public? 🤪",
    "Have you ever accidentally revealed a secret you shouldn’t have? 🤭",
    "What’s the last lie you told? 🤔",
    "What’s the longest you’ve gone without showering? 🚿",
    "Have you ever had a crush on someone you shouldn’t have? 🫢",
    "What’s your most embarrassing social media post? 📸",
    "What’s the craziest thing you’ve ever done for love? 💌",
    "Have you ever eavesdropped on someone’s conversation? 👂",
    "What’s the most ridiculous outfit you’ve ever worn? 👗",
    "What’s something you’ve never told your best friend? 🤐",
    "Have you ever been caught talking to yourself? 🗣️",
    "What’s the most trouble you’ve gotten into at school? 🏫",
    "What’s the worst gift you’ve ever received? 🎁",
    "Have you ever had a wardrobe malfunction? 🩳",
    "What’s your most irrational fear? 🕷️",
    "Have you ever broken the law? 🚓",
    "What’s the worst date you’ve ever been on? 🥀",
    "Have you ever pretended to be someone you’re not? 🤡",
    "What’s the most embarrassing thing you’ve done in front of your crush? 😳",
    "What’s something you’ve done that you’re ashamed of? 🙈",
    "Have you ever lied about your age? 🎂",
    "What’s the longest you’ve stayed awake? 🕒",
    "What’s the worst lie you’ve ever been caught in? 😬",
    "Have you ever snooped through someone’s things? 🔍",
    "What’s the most embarrassing thing you’ve done while drunk? 🍺",
    "Have you ever kissed someone you regret? 💋",
    "What’s the weirdest thing you’ve ever Googled? 🖥️",
    "Have you ever laughed so hard you peed your pants? 🤣",
    "What’s your most embarrassing text message? 📲",
    "Have you ever sent a message to the wrong person? 🙊",
    "What’s the most childish thing you still do? 🍼",
    "What’s your weirdest nickname? 🐒",
    "Have you ever lied to a friend to get out of something? 🤥",
    "What’s a secret you’ve kept from your family? 🏠",
    "Have you ever had a crush on a friend’s partner? 😬",
    "What’s the most money you’ve ever spent on something silly? 💸",
    "Have you ever been rejected by someone you liked? 💔",
    "What’s your most awkward moment in school? 🎒",
    "Have you ever lied about liking someone’s cooking? 🍳",
    "What’s the most embarrassing photo of yourself? 📷",
    "Have you ever had a crush on a celebrity? 🌟",
    "What’s a bad habit you’re embarrassed about? 🤦",
    "Have you ever copied someone else’s homework? 📚",
    "What’s the biggest mistake you’ve ever made? ❌",
    "Have you ever been caught sneaking out? 🕵️",
    "What’s your most embarrassing moment in public? 🫣",
    "Have you ever been in love with two people at the same time? 😵‍💫",
    "What’s the weirdest excuse you’ve ever made? 📝",
    "Have you ever lied to your boss? 👔",
    "What’s your weirdest obsession? 🤯",
    "Have you ever kissed someone you didn’t like? 😬",
    "What’s your weirdest guilty pleasure? 🍿",
    "Have you ever written a love letter? ✉️",
    "What’s something silly you’ve cried over? 😢",
    "Have you ever been caught lying in a game of truth or dare? 🎲",
    "What’s the most daring thing you’ve ever done? 🏞️",
    "Have you ever told a secret you weren’t supposed to? 🤭",
    "What’s the most embarrassing thing you’ve done for attention? 🫢",
    "Have you ever stalked someone online? 🖱️",
    "What’s the strangest thing you’ve ever bought? 🛒",
    "Have you ever been jealous of someone’s success? 🏆",
    "What’s a song you’re embarrassed to admit you love? 🎶",
    "Have you ever faked a friendship? 🤔",
    "What’s the most awkward compliment you’ve received? 🙃",
    "Have you ever flirted with someone just to get something? 😏",
    "What’s a secret you’ve never told anyone? 🤐",
    "Have you ever lied about your relationship status? 💑",
    "What’s the weirdest thing you’ve eaten? 🍜",
    "Have you ever forgotten someone’s name after meeting them? 😅",
    "What’s your most embarrassing memory at a party? 🎉",
    "Have you ever been caught checking someone out? 😳",
    "What’s a rumor you started or spread? 🗣️",
    "Have you ever been caught in an awkward situation with your crush? 💞",
    "What’s the longest lie you’ve kept going? ⏳",
    "Have you ever ghosted someone? 👋",
    "What’s the most awkward gift you’ve ever given? 🎁",
    "Have you ever embarrassed yourself in front of your family? 👨‍👩‍👧‍👦",
    "What’s something you did as a kid that still embarrasses you? 🧒",
    "Have you ever lied about your plans to avoid someone? 📅",
    "What’s the most awkward thing someone’s said to you? 😬",
    "Have you ever had an embarrassing social media moment? 🖼️",
    "What’s your most embarrassing moment in school? 🏫",
    "Have you ever been caught daydreaming? 🌥️",
    "What’s the most ridiculous thing you’ve ever cried about? 😭",
    "Have you ever kept a big secret from your parents? 🤐",
    "What’s something you’ve done that you can’t believe you got away with? 😎",
    "Have you ever faked knowing something to impress someone? 🎭",
    "What’s the most random thing you’ve ever Googled? 💻",
    "Have you ever made up a fake excuse to leave a date? 🚪",
    "What’s your weirdest bathroom habit? 🚻",
    "Have you ever had a crush on someone much older? 👴",
    "What’s the most awkward text you’ve received? 📩",
    "Have you ever fallen asleep in public? 💤",
    "What’s the most embarrassing story about yourself that someone else knows? 🗣️",
    "Have you ever been scared of something silly? 😅",
    "What’s the most awkward interaction you’ve had with a stranger? 🤷",
    "Have you ever lied during truth or dare? 🎲",
    "Have you ever forgotten an important event or date? 📅",
    "What’s the weirdest thing you’ve ever done alone? 🤔",
    "Have you ever been caught singing or dancing in the mirror? 🪞",
    "What’s the most embarrassing thing you’ve done in front of your parents? 🫣",
    "Have you ever lied about liking a gift? 🎁",
    "What’s the most awkward conversation you’ve ever had? 🗨️",
    "Have you ever laughed at an inappropriate moment? 😂",
    "What’s the most unusual outfit you’ve worn in public? 👕",
    "Have you ever forgotten someone’s birthday? 🎂",
    "What’s your most awkward celebrity encounter? 🌟",
    "Have you ever been caught sneaking food? 🍪",
    "What’s the most embarrassing photo in your phone? 📱",
    "Have you ever told a friend’s secret? 🤐",
    "What’s your biggest fear that seems silly? 🐝",
    "Have you ever stalked someone on social media? 🖱️",
    "What’s the worst haircut you’ve ever had? ✂️",
    "Have you ever lied to make someone feel better? 🤥",
    "What’s the most awkward compliment you’ve ever given? 🙃",
    "Have you ever had a crush on someone in this room? 😳",
    "What’s your worst habit you still haven’t broken? 🫠",
    "Have you ever been embarrassed by your own laugh? 🤣",
    "What’s the most embarrassing thing you’ve done on a date? 💌",
    "Have you ever worn something inside out by accident? 👚",
    "What’s the longest you’ve gone without brushing your teeth? 🪥",
    "Have you ever pretended to know something you didn’t? 🎭",
    "What’s your most awkward moment with a teacher? 👩‍🏫",
    "Have you ever accidentally texted the wrong person? 📩",
    "What’s your most embarrassing childhood story? 🧒",
    "Have you ever lied to avoid getting in trouble? 😬",
    "What’s the most ridiculous dare you’ve ever completed? 🎲",
    "Have you ever lied to impress a crush? 😏",
    "What’s your weirdest superstition? 🪄",
    "Have you ever had an awkward meeting with an ex? 💔",
    "What’s the grossest thing you’ve ever done? 🤢",
    "Have you ever been caught staring at someone? 👀",
    "What’s the silliest fear you’ve ever had? 😅",
    "Have you ever fallen in front of a crowd? 🫣",
    "What’s the most ridiculous thing you’ve believed as a kid? 🧚",
    "Have you ever been caught sleeping in class? 🛌",
    "What’s the most awkward thing you’ve done in a group? 🫠",
    "Have you ever been caught faking something? 🤡",
    "What’s the most random thing you’ve ever lied about? ❓",
    "Have you ever talked about someone behind their back? 🗣️",
    "What’s the most awkward moment you’ve had at work? 🏢",
    "Have you ever cried over a silly argument? 😭",
    "What’s the most embarrassing thing you’ve done while drunk? 🍹",
    "Have you ever had an embarrassing online fail? 💻",
    "What’s the weirdest thing you’ve ever done for attention? 🌟",
    "Have you ever tripped over nothing? 🫢",
    "What’s the most cringe-worthy thing you’ve ever said to someone? 😬",
    "Have you ever lied to your parents about where you were? 🏠",
    "What’s the most embarrassing story your parents tell about you? 😅",
    "Have you ever been caught lying in a game of truth or dare? 🎲",
    "What’s the worst decision you’ve made on a dare? 🤦",
    "Have you ever been caught snooping on someone? 👀",
    "What’s the most awkward thing you’ve overheard? 🗣️",
    "Have you ever lied about liking a movie or book? 📖",
    "What’s the worst excuse you’ve ever made? 🤥",
    "Have you ever embarrassed yourself at a party? 🎉",
    "What’s the most awkward moment you’ve had in an elevator? 🛗",
    "Have you ever forgotten someone’s name right after meeting them? 🤦",
    "What’s the worst advice you’ve ever given someone? 📝",
    "Have you ever lied about your plans to cancel on someone? 🗓️",
    "What’s the most embarrassing outfit you’ve worn in public? 👔",
    "Have you ever fallen asleep somewhere strange? 💤",
    "What’s the most awkward misunderstanding you’ve had? 🤷",
    "Have you ever cried during a commercial? 📺",
    "What’s the most embarrassing nickname someone’s given you? 🐤",
    "Have you ever panicked in a public speaking situation? 🗣️",
    "What’s the weirdest thing you’ve ever kept as a keepsake? 🗃️",
    "Have you ever accidentally insulted someone? 🫣",
    "What’s the most embarrassing misunderstanding you’ve had? 🤔",
    "Have you ever been caught singing in public? 🎤",
    "What’s the weirdest food combination you’ve ever tried? 🍕",
    "Have you ever laughed at a joke you didn’t understand? 🤨",
    "What’s the most embarrassing story about yourself that you’ve shared? 🗣️",
    "Have you ever tripped while walking in front of someone you liked? 😳",
    "What’s the most embarrassing thing you’ve done in front of strangers? 😅",
    "Have you ever tried to impress someone and failed miserably? 😵",
    "What’s the worst lie you’ve ever been caught in? 🕵️",
    "Have you ever been caught staring at your crush? 👀",
    "What’s your most awkward social media post? 📱",
    "Have you ever faked knowing about a topic in a conversation? 🤭",
    "What’s your most embarrassing mistake at school? 🎓",
    "Have you ever been caught sneaking out of the house? 🚪",
    "What’s your most embarrassing karaoke moment? 🎶",
    "Have you ever had a wardrobe malfunction in public? 👗",
    "What’s the most awkward text you’ve sent to the wrong person? 📲",
    "Have you ever been caught lying to your best friend? 🫢",
    "What’s the most embarrassing thing you’ve ever done at work? 🏢",
    "Have you ever been scared of a harmless animal? 🐇",
    "What’s the most awkward thing you’ve accidentally said in public? 🗣️",
    "Have you ever forgotten to mute yourself on a call? 🎧",
    "What’s the worst text autocorrect fail you’ve had? 📲",
    "Have you ever danced like no one was watching, but someone was? 💃",
    "What’s the longest you’ve gone without washing your hair? 🛀",
    "Have you ever lied to get out of a meeting? 🕒",
    "What’s the weirdest thing you’ve done to impress a crush? 😏",
    "Have you ever been caught daydreaming in a serious situation? 🌥️",
    "What’s the strangest thing you’ve ever collected? 🗃️",
    "Have you ever lied about being busy to avoid someone? 📅",
    "What’s the most embarrassing gift you’ve ever given? 🎁",
    "Have you ever tripped in front of a large crowd? 🫠",
    "What’s your weirdest experience at a party? 🎉",
    "Have you ever been caught dancing in your room? 🕺",
    "What’s the most embarrassing thing you’ve accidentally said to someone? 🤦",
    "Have you ever sent a text about someone to that same person? 🙊",
    "What’s the most awkward moment you’ve had on a video call? 📹",
    "Have you ever cried in public? 😢",
    "What’s the worst haircut decision you’ve made? ✂️",
    "Have you ever had a crush on someone completely unexpected? 😳",
    "What’s the worst thing you’ve ever been caught doing at school? 🏫",
    "Have you ever been caught sleeping at work or school? 💤",
    "What’s the strangest thing you’ve ever Googled late at night? 🌙",
    "Have you ever forgotten someone’s name in the middle of introducing them? 🤦",
    "What’s the most embarrassing trend you’ve followed? 🕶️",
    "Have you ever walked into the wrong room or building? 🚪",
    "What’s your most embarrassing social media comment? 💻",
    "Have you ever laughed so hard you made a scene? 😂",
    "What’s the most cringe-worthy thing you’ve said to a crush? 😬",
    "Have you ever panicked and said something completely random? 🤔",
    "What’s the weirdest thing you’ve ever done when no one was watching? 🫣",
    "Have you ever accidentally worn mismatched shoes? 👟",
    "What’s the most awkward photo you’ve been tagged in? 📸",
    "Have you ever lied to get out of a family gathering? 👨‍👩‍👧",
    "What’s the most embarrassing thing that’s happened to you in a store? 🛒",
    "Have you ever waved back at someone who wasn’t waving at you? 👋",
    "What’s the worst thing you’ve spilled on yourself in public? 🥤",
    "Have you ever been caught sneaking snacks? 🍫",
    "What’s the most ridiculous thing you’ve cried over? 😭",
    "Have you ever been scared of a movie meant for kids? 🍿",
    "What’s your most embarrassing wardrobe mistake? 🧥",
    "Have you ever accidentally replied to all in an email? 📧",
    "What’s the weirdest lie you’ve told as a child? 🧒",
    "Have you ever had a crush on someone you’ve only met online? 🌐",
    "What’s the most embarrassing thing you’ve done at a wedding? 💒",
    "Have you ever been caught singing in your car at a stoplight? 🚗",
    "What’s your most awkward moment with a stranger? 🫢",
    "Have you ever accidentally worn your clothes backward? 👕",
    "What’s the most embarrassing typo you’ve sent in a text? 📩",
    "Have you ever been caught talking to yourself? 🗣️",
    "What’s the weirdest dream you’ve ever shared with someone? 🛌",
    "Have you ever lied about knowing how to do something? 🤥",
    "What’s the most embarrassing nickname you’ve ever had? 🐻",
    "Have you ever been caught playing with something meant for kids? 🧸",
    "What’s the most ridiculous excuse you’ve made for being late? 🕒",
    "Have you ever had a crush on a fictional character? 📚",
    "What’s the worst fashion trend you’ve participated in? 👗",
    "Have you ever cried over a book or movie character? 📖",
    "What’s the strangest thing you’ve said in your sleep? 😴",
    "Have you ever been caught pretending to know the lyrics to a song? 🎵",
    "What’s your most awkward encounter with a teacher? 🏫",
    "Have you ever sent a text message full of emojis by accident? 😅",
    "What’s the most embarrassing thing you’ve done while shopping? 🛍️",
    "Have you ever been caught wearing mismatched socks? 🧦",
    "What’s the most awkward moment you’ve had with a coworker? 👔",
    "Have you ever been scared of something completely harmless? 🫣",
    "What’s the most awkward thing you’ve posted online? 🌐",
    "Have you ever forgotten you were on camera during a video call? 🎥",
    "What’s your most awkward experience with a customer or client? 💼",
    "Have you ever walked into a glass door or wall? 🪟",
    "What’s the most ridiculous thing you’ve done while bored? 😴",
    "Have you ever been caught staring into space? 🌌",
    "What’s the most embarrassing way you’ve injured yourself? 🩹",
    "Have you ever been caught doodling in an important meeting or class? ✏️",
    "What’s the weirdest thing you’ve done out of curiosity? 🤔",
    "Have you ever been caught singing in the shower? 🚿",
    "What’s the most awkward misunderstanding you’ve had with a friend? 🫠",
    "Have you ever cried during a conversation with someone? 🥹",
    "What’s the most awkward thing you’ve forgotten to do? 🫣",
    "Have you ever been scared by your own reflection? 🪞",
    "What’s the most embarrassing question you’ve asked someone? ❓",
    "Have you ever fallen asleep at an inappropriate time? 🛌",
    "What’s the most ridiculous thing you’ve done on a dare? 🎲",
    "Have you ever had an awkward moment while cooking? 🍳",
    "What’s the most awkward group project experience you’ve had? 👩‍🏫",
    "Have you ever been caught wearing something that didn’t match? 🧥",
    "What’s your most embarrassing karaoke moment? 🎤",
    "Have you ever laughed at a joke you didn’t understand? 🤨",
    
    # New truths from the provided list
    "What was your worst rejection? 💔",
    "What's the most embarrassing thing you've done? 😱",
    "What's the grossest thing you've done? 🤮",
    "When were you last embarrassed? 😖",
    "What's your least favorite food? 🍽️",
    "Do you believe in ghosts? 👻",
    "Who's the last person you texted? 📱",
    "What's the biggest lie you've told? 🤥",
    "Who's your celebrity crush? 🌟",
    "What's your ideal date? ❤️",
    "When was your first kiss? 💏",
    "Who would you marry on the spot? 💍",
    "Do you believe in angels? 👼",
    "What's your greatest fear? 😨",
    "Have you ever cheated on someone? 💔",
    "What's your favorite animal? 🐾",
    "What's the weirdest text you've ever received? 📲",
    "Do you like spicy foods? 🌶️",
    "Name the strangest fact you know. 🤯",
    "What's a silly thing you used to do as a kid? 😂",
    "What's your favorite joke? 🤣",
    "When was the last time you cried with laughter? 😂",
    "Do you think you're a good singer? 🎤",
    "What's your phone's lock screen? 📱",
    "Have you ever written a love poem? 💕",
    "Have you ever had a crush on a teacher? 🍎",
    "Who's someone you pretend to like but don't? 🤨",
    "Have you ever been pulled over? 🚨",
    "What's the naughtiest thing you've ever done? 😈",
    "What's the most daring thing you've done? 💪",
    "Have you ever stalked someone on social media? 🕵️",
    "Describe your best kiss. 💋",
    "If you had to kiss a family member, who would it be? 😱",
    "Would you rather hands for feet or feet for hands? 🤪",
    "Have you ever gone skinny dipping? 🏊",
    "How many people have you hooked up with? 💏",
    "Were you ever in a choir? 🎶",
    "What do you like the most about yourself? 🌟",
    "Have you ever pretended to be on the phone to avoid someone? 📱",
    "What's your biggest secret? 🤫",
    "If I gave you $100, what would you do with it? 💰",
    "How many guy contacts are in your phone? 📞",
    "How many girl contacts are in your phone? 📱",
    "Is there anything you'd change about your life? 🤔",
    "Who do you hate the most and why? 😠",
    "Have you ever kissed someone with your eyes open? 👀",
    "What's your guilty pleasure? 😏",
    "What song do you sing in the shower? 🚿",
    "Have you ever blamed someone for something you did? 🙊",
    "What's your favorite board game? 🎲",
    "Describe the wildest dream you've ever had? 💭",
    "What's your favorite ice cream flavor? 🍦",
    "Are you a morning or night person? 🌞🌙",
    "If you could marry a Disney character, who would it be? 👑",
    "On a scale of 1 to 10, how attractive am I? 😉",
    "What's the weirdest food combination you like? 🍽️",
    "Ketchup or mustard? 🥫",
    "What is your favorite Halloween costume? 🎃",
    "Were you a cute baby? 👶",
    "What's the last movie you watched? 🎬",
    "What's one thing you can't live without? ❤️",
    "What food could you eat for the rest of your life? 🍽️",
    "When did you start liking me? 😏",
    "What's the worst thing an ex has done to you? 💔",
    "When do you feel the most like yourself? 🌈",
    "Who's your favorite celebrity? 🌟",
    "What's the strangest thing you've Googled? 🤨",
    "Tell me about a time when you were scared? 😱",
    "Have you ever farted in a public space? 💨",
    "Describe your wildest weekend? 🎉",
    "Would you rather lick your shoe or the sidewalk? 👅",
    "If you could be a TV character, who would you be? 📺",
    "What's your worst habit? 🙈",
    "If I was in your room, what would I be surprised to find? 🤔",
    "Describe your dream vacation? ✈️",
    "What makes you jealous? 😤",
    "What do you like the most about me? 💕",
    "What's the scariest dream you've ever had? 😱",
    "What's your biggest insecurity? 🥺",
    "What's your weirdest habit? 🤪",
    "Would you rather marry a rich or kind person? 💑"
]

# List of flirty dares
DARE_LIST = [
    "DM your crush 📩",
    "Send me a selfie making the funniest face you can 😂",
    "Send a love letter to a random Instagram follower 💌",
    "Post your most embarrassing story on Facebook 🙈",
    "Eat a spoonful of mayonnaise and send me a pic 🥄",
    "Send me your most embarrassing photo 📸",
    "Take a bite out of an onion 🧅",
    "Bark like a dog for 1 minute straight 🐶",
    "Send me a screenshot of your last text conversation 📱",
    "Text a family member, 'I have something to tell you' 😱",
    "Slide into a celebrity's DMs 🌟",
    "Ask your crush out 💖",
    "Message your first crush, 'I still love you' 💘",
    "Text your crush and ask, 'Will you marry me?' 💍",
    "Mix ketchup and cottage cheese together and take a big bite 🤢",
    
    # Existing flirty dares
    "Send a flirty message to your crush 💕",
    "Give your best flirty wink to someone in the group 😉",
    "Do your best romantic dance move 💃",
    "Share your most recent flirty chat (hide the name) 📱",
    "Call someone and tell them they're cute 📞",
    # ... (continue adding all previous dares)
    "Do your best impersonation of someone in the room for one minute. 🎭",
    "Call a random person and sing them a song. 🎶",
    "Let someone write a word on your forehead with a marker. ✍️",
    "Eat a spoonful of a spicy condiment from the fridge. 🌶️",
    "Post an embarrassing photo of yourself on social media. 📸",
    "Talk in an accent of the group's choice for the next 10 minutes. 🗣️",
    "Do 20 push-ups while singing a song. 💪",
    "Wear socks on your hands for the next 5 rounds. 🧦",
    "Text your crush and tell them you like them. ❤️",
    "Do your best dance moves for one minute without music. 💃",
    "Let the group choose a word you have to include in every sentence for the next 5 minutes. 🗨️",
    "Do a blindfolded makeup challenge with someone. 🎨",
    "Share the last thing you searched for on your phone. 🔍",
    "Let someone draw on your face with eyeliner or a marker. 😜",
    "Eat a piece of food without using your hands. 🍎",
    "Call your best friend and speak in a made-up language for 2 minutes. 📞",
    "Take a selfie making the funniest face and send it to someone random. 🤳",
    "Wear someone else’s shoes on your hands until the next round. 👟",
    "Let the group choose a silly outfit for you to wear for the next 3 rounds. 👕",
    "Sing the chorus of your favorite song out loud. 🎤",
    "Pretend to be a cat and meow for 2 minutes. 🐱",
    "Do your best impression of a celebrity until someone guesses who it is. 🌟",
    "Balance a book on your head and walk across the room. 📚",
    "Swap clothes with someone for the next 3 rounds. 👗",
    "Let someone tickle you for 30 seconds without moving. 😂",
    "Act like a chicken until it’s your turn again. 🐔",
    "Eat a slice of lemon or lime without making a face. 🍋",
    "Let someone send a random emoji from your phone to a contact. 📲",
    "Speak only in rhymes for the next 5 minutes. 🧙",
    "Do your best runway walk across the room. 🚶",
    "Drink a glass of water while standing on one leg. 💧",
    "Try to lick your elbow and let others take a picture. 😝",
    "Let someone else do your hairstyle however they want. ✂️",
    "Sing everything you say for the next 5 minutes. 🎵",
    "Try to juggle three random items from the room. 🎲",
    "Do your best animal impression until someone guesses what you are. 🦁",
    "Tell a fake but convincing story about how you got your nickname. 🤥",
    "Let someone text your mom something funny from your phone. 📱",
    "Eat a spoonful of sugar or salt and keep a straight face. 🥄",
    "Wear a blanket as a cape for the next 5 minutes. 🦸",
    "Make up a poem about the person sitting next to you. 🖋️",
    "Spin around 10 times and then try to walk in a straight line. 🔄",
    "Speak in a robot voice for the next 3 minutes. 🤖",
    "Let someone paint one of your nails a random color. 💅",
    "Take an awkward family-style photo with the group. 📸",
    "Imitate your favorite cartoon character for 2 minutes. 🐭",
    "Call someone and ask them to guess what sound you’re making. 🎶",
    "Wear socks on your ears for the next 3 rounds. 🧦",
    "Let someone pick a random photo from your gallery and share it. 📷",
    "Dance to a song chosen by the group for 30 seconds. 🕺",
    "Speak only in questions for the next 5 minutes. ❓",
    "Draw a mustache on your face with eyeliner or marker. 👨",
    "Hold your breath for 15 seconds while everyone counts. 🌬️",
    "Talk in a baby voice until your next turn. 🍼",
    "Eat a weird combination of two foods suggested by the group. 🍴",
    "Pretend you’re a statue for 2 minutes. 🗿",
    "Do a cartwheel or attempt one. 🤸",
    "Pretend to take a fake shower for 30 seconds. 🚿",
    "Let someone change your phone's wallpaper to anything they choose. 📱",
    "Hop on one leg while reciting the alphabet. 🦵",
    "Pretend to be someone’s pet dog for the next 3 minutes. 🐕",
    "Let the group pick a song and perform karaoke to it. 🎤",
    "Create a story on the spot with five random words chosen by the group. 📚",
    "Act like you’re in a TV commercial for the next 2 minutes. 📺",
    "Walk across the room doing your best dinosaur impression. 🦖",
    "Do your best evil villain laugh. 😈",
    "Let someone draw a funny tattoo on your arm. 🖊️",
    "Talk like a pirate for the next 5 minutes. 🏴‍☠️",
    "Act like you’re swimming on the floor for 30 seconds. 🏊",
    "Pretend to cry dramatically until it’s your next turn. 😭",
    "Give a motivational speech about why socks are important. 🧦",
    "Take a bite of food while blindfolded and guess what it is. 😋",
    "Let someone write something funny on your hand. ✋",
    "Balance a spoon on your nose for 15 seconds. 🥄",
    "Try to do 10 jumping jacks while holding a book. 📖",
    "Act like your favorite animal until someone guesses it. 🐒",
    "Hold a straight face while someone tries to make you laugh. 😐",
    "Stand on one leg and try to recite the alphabet backward. 🔤",
    "Speak in slow motion for the next 2 minutes. 🕐",
    "Let the group design a funny new hairstyle for you. 💇",
    "Pretend to be a news anchor and report on a made-up story. 📰",
    "Walk backward across the room while clapping your hands. 👏",
    "Pretend to do the weather forecast for the day. ☀️",
    "Wear a towel or blanket as a superhero cape until your next turn. 🦸",
    "Call a random friend and ask them if they believe in aliens. 👽",
    "Let the group choose your new nickname for the next hour. 🎭",
    "Post a funny dance video on your social media. 📱",
    "Let someone give you a silly nickname for the rest of the game. 🏷️",
    "Pretend you're a news anchor for the next minute and give a weather report. 🌤️",
    "Imitate a celebrity for the next 3 minutes. 🌟",
    "Take a silly selfie and set it as your profile picture for an hour. 🤳",
    "Let someone blindfold you and feed you something random. 🍴",
    "Do 15 jumping jacks while singing your favorite song. 🎶",
    "Walk around the room pretending to be a model on a runway. 👠",
    "Let someone send a random text from your phone to your best friend. 📲",
    "Post a status on social media about how much you love pineapple pizza. 🍍🍕",
    "Speak in a foreign accent for the next 5 minutes. 🎤",
    "Let someone draw a funny picture on your face with a marker. ✍️",
    "Give a dramatic reading of a random text message in your phone. 📱",
    "Do your best impression of a baby for one minute. 👶",
    "Talk like a robot until it’s your next turn. 🤖",
    "Try to juggle three items for 30 seconds. 🎲",
    "Pretend you’re a waiter and serve everyone a drink. 🍹",
    "Send a voice message to your mom saying something silly. 🎙️",
    "Call a friend and pretend you don’t know them for a minute. 📞",
    "Dance like a chicken for 1 minute. 🐔",
    "Try to do a cartwheel. 🤸‍♂️",
    "Let someone pick a random item in the room and you have to use it for the next minute. 📦",
    "Talk in third person for the next 10 minutes. 👤",
    "Make an animal noise every time you speak for the next 5 minutes. 🐯",
    "Do an impression of your favorite character for one minute. 🦸‍♂️",
    "Let someone else choose your next outfit and you have to wear it for the next 30 minutes. 👚",
    "Try to touch your toes without bending your knees for 30 seconds. 🤸‍♀️",
    "Pretend to be an opera singer for 1 minute. 🎶",
    "Walk around the room like a zombie for 2 minutes. 🧟‍♂️",
    "Let someone take an embarrassing photo of you and post it. 📸",
    "Do your best dance moves to a song of the group’s choice. 💃",
    "Make an embarrassing confession to the group. 😳",
    "Do a dramatic reading of a text from your phone. 📝",
    "Let someone draw a silly picture on your arm with a pen. ✍️",
    "Eat a piece of food without using your hands. 🍎",
    "Pretend you’re a cat for 2 minutes. 🐱",
    "Send a random emoji to the last person you texted. 📲",
    "Put on socks on your hands and act like a cat for the next 2 minutes. 🐾",
    "Pretend to be a teacher and give the group a lesson. 👩‍🏫",
    "Let someone send a message from your phone to any contact. 📲",
    "Try to do the splits for 30 seconds. 🤸‍♀️",
    "Tell a joke in a dramatic fashion. 😂",
    "Dance with no music for 1 minute. 🎵",
    "Speak only in song lyrics for the next 5 minutes. 🎤",
    "Do a dramatic reading of a random text conversation. 📱",
    "Pretend to be a famous movie star for the next 5 minutes. 🎬",
    "Wear your clothes backward for the next 10 minutes. 👕",
    "Do your best animal impression and let the group guess what it is. 🦁",
    "Try to hula hoop for 1 minute. 🪃",
    "Give a random compliment to everyone in the group. 😊",
    "Act like you’re on a talk show and interview someone. 🎤",
    "Make a silly face for 30 seconds and keep it. 🤪",
    "Do your best impression of a famous cartoon character. 🐭",
    "Speak in only rhymes for the next 5 minutes. 🎶",
    "Dance in place without stopping for 1 minute. 💃",
    "Let someone choose an outfit for you to wear for the next hour. 👗",
    "Try to whistle while doing a funny dance. 🎶",
    "Send a random meme to your mom. 📲",
    "Pretend to be a waiter or waitress and take an order from everyone in the group. 🍴",
    "Walk in a circle and make up a song about your surroundings. 🎶",
    "Call your best friend and speak in riddles for 1 minute. 🕵️‍♂️",
    "Try to touch your nose with your tongue. 👅",
    "Create a funny sound every time you speak for the next 5 minutes. 🎤",
    "Sing everything you say until it’s your turn again. 🎵",
    "Do an impression of your favorite animal for 2 minutes. 🐒",
    "Let someone take a funny video of you doing a dance. 📱",
    "Post an embarrassing story on social media. 📱",
    "Pretend to be a robot for the next 2 minutes. 🤖",
    "Do a cartwheel and then stand still for 1 minute. 🤸‍♀️",
    "Try to lick your elbow for 30 seconds. 🫣",
    "Pretend to be a supervillain for 1 minute. 🦹‍♀️",
    "Give a dramatic reading of a text message from your phone. 📱",
    "Dance for 1 minute to a song chosen by the group. 🎶",
    "Make a funny video pretending to be a news reporter. 📹",
    "Walk backward for the next 2 minutes. 👣",
    "Pretend to be a ballerina for the next 2 minutes. 🩰",
    "Do a dramatic reading of a random text conversation out loud. 📝",
    "Do an impression of someone in the room until they guess who it is. 🕵️‍♀️",
    "Pretend you are a DJ and introduce the next song to the group. 🎧",
    "Act like you’re on a cooking show and give a recipe for something random. 🍳",
    "Pretend you’re a mannequin and stand still for 2 minutes. 🧍‍♂️",
    "Do 20 push-ups while singing your favorite song. 💪🎤",
    "Pretend you’re a character from your favorite movie for the next 3 minutes. 🎥",
    "Let someone take a funny picture of you and make it your profile picture. 📸",
    "Call a friend and tell them you’re on a mission to save the world. 🌎",
    "Try to juggle 3 items at the same time for 30 seconds. 🎲",
    "Do your best impression of a famous person until someone guesses who it is. 👤",
    "Let someone pick an emoji and use it as your only response for 10 minutes. 😂",
    "Dance like no one’s watching for 1 minute. 🕺",
    "Pretend you’re a famous person for the next 2 minutes. 👑",
    "Speak in song lyrics for the next 3 minutes. 🎤",
    "Pretend to be a movie star and take a photo like you’re on the red carpet. 🎬",
    "Pretend you are a sports commentator for the next 2 minutes. 🎙️",
    "Let someone send a random emoji to your best friend. 📲",
    "Walk around like a penguin for the next minute. 🐧",
    "Do your best robot dance for 1 minute. 🤖",
    "Try to juggle 2 items for 30 seconds. 🎲",
    "Pretend you’re a superhero and strike your best superhero pose. 🦸‍♀️",
    "Give a 1-minute speech about why you should be the next president. 🗣️",
    "Do a silly dance for 1 minute without stopping. 💃",
    "Pretend to be a waiter or waitress and take a silly order from everyone in the group. 🍽️",
    "Call your friend and sing ‘Happy Birthday’ to them, even if it’s not their birthday. 🎶",
    "Let someone send a text to your crush on your behalf. 💌",
    "Do your best impression of someone in the room for 1 minute. 🎭",
    "Speak in a slow motion voice for the next 2 minutes. 🐢",
    "Act like a statue until someone taps you. 🗿",
    "Pretend you’re on a cooking show and explain how to make a sandwich. 🍞",
    "Give a dramatic reading of the last text you sent. 📱",
    "Send a random meme to your parent. 📲",
    "Do your best celebrity impression until someone guesses who it is. 🌟",
    "Pretend to be a rockstar and perform for the next 2 minutes. 🎸",
    "Do an impression of a robot and move like one for 1 minute. 🤖",
    "Do 10 push-ups and then walk like a crab for 30 seconds. 🦀",
    "Speak in riddles for the next 5 minutes. 🕵️‍♂️",
    "Send a random, funny GIF to your best friend. 📲",
    "Pretend you’re a spy on a secret mission for the next 2 minutes. 🕵️‍♀️",
    "Do your best impression of an animal until someone guesses what it is. 🦁",
    "Do a silly dance and don’t stop until someone gives you a compliment. 💃",
    "Pretend you’re a stand-up comedian for 2 minutes and tell jokes. 🎤",
    "Do a dramatic reading of your favorite song lyrics. 🎶",
    "Try to do a handstand for 30 seconds. 🤸‍♂️",
    "Let someone write a funny message on your forehead with a marker. ✍️",
    "Do your best impression of a famous cartoon character for 1 minute. 🦸‍♂️",
    "Talk in a different accent for the next 5 minutes. 🎤",
    "Post a silly video of yourself doing something random on your social media. 📱",
    "Act like you’re a news anchor reporting live for the next 2 minutes. 📰",
    "Pretend you’re a model and do a runway walk across the room. 👠",
    "Send a random song to your sibling and say, 'This is your new jam!' 🎶",
    "Do 15 jumping jacks and make silly noises while doing them. 🦸",
    "Let someone make a funny Snapchat filter for you and post it. 🤳",
    "Take a funny selfie and make it your profile picture. 🤳",
    "Post a funny dance video to your social media with the caption 'Can’t stop, won’t stop!' 🎶",
    "Pretend you’re a dog and ‘bark’ every time you speak. 🐕",
    "Dance in place like no one’s watching for 1 minute. 💃",
    "Do a silly walk across the room and let everyone watch. 🚶‍♀️",
    "Talk like a pirate for the next 5 minutes. 🏴‍☠️",
    "Pretend you are a tree and freeze in place for 1 minute. 🌳",
    "Make a funny video pretending you’re a celebrity for 2 minutes. 🌟",
    "Do a cartwheel and then pose like a superhero. 🦸‍♂️",
    "Try to do a split and hold it for 10 seconds. 🤸‍♀️",
    "Pretend you’re a famous singer and give an impromptu concert for the group. 🎤",
    "Take a video of yourself trying to rap and post it. 🎶",
    "Do an impression of a famous historical figure for 1 minute. 🏛️",
    "Post a random song lyric on your story and ask people to guess the song. 🎤",
    "Dance to a song without any music for 1 minute. 💃",
    "Try to stand on one foot for 1 minute. 🦶",
    "Do 10 squats while singing your favorite song. 🎶",
    "Call your friend and act like you’re on a game show. 🎤",
    "Send a picture of your funniest face to your best friend. 🤪",
    "Do a yoga pose and hold it for 1 minute. 🧘‍♂️",
    "Let someone post a funny video from your camera roll to your story. 📲",
    "Act like you’re at the Oscars and give an acceptance speech for 1 minute. 🏆",
    "Do a dramatic reading of your latest text messages. 📱",
    "Try to whistle while doing a funny dance for 1 minute. 🎶",
    "Post a picture of something embarrassing and caption it 'Throwback.' 📸",
    "Dance like you’re at a wedding for 1 minute. 💃",
    "Pretend you’re a fashion model and do a slow-motion runway walk. 🕺",
    "Make a random sound every time you speak for the next 5 minutes. 🐯",
    "Let someone write something funny on your hand with a marker. ✍️",
    "Give a one-minute speech about why your favorite food is the best. 🍕",
    "Walk backward for the next 2 minutes without stopping. 👣",
    "Act like a robot and talk like one for the next 3 minutes. 🤖",
    "Pretend you’re a dinosaur for the next minute. 🦖",
    "Do a funny impersonation of your favorite movie character. 🎬",
    "Talk in a high-pitched voice for the next 5 minutes. 🎤",
    "Try to do a cartwheel and hold the pose for 10 seconds. 🤸‍♀️",
    "Pretend you’re in a music video for the next 2 minutes and perform. 🎶",
    "Try to make yourself laugh out loud for 1 minute. 😂",
    "Do a 30-second dance routine to a song you don’t know. 🎶",
    "Pretend you’re in a talk show and interview someone in the group. 🎤",
    "Imitate your favorite celebrity for the next 2 minutes. 🌟",
    "Do a funny impersonation of someone in the room until they guess who it is. 🕵️‍♂️",
    "Pretend you’re a magician and perform a ‘magic trick’ for the group. 🎩",
    "Pretend you’re an alien and make up a story about visiting Earth. 👽",
    "Walk around the room like a penguin for 1 minute. 🐧",
    "Do a dramatic reading of a random text from your phone. 📱",
    "Try to make up a new dance move and teach it to the group. 💃",
    "Send a funny voice message to your best friend. 📲",
    "Act like a famous singer and perform one of their songs. 🎤",
    "Pretend to be a superhero and save someone from an imaginary villain. 🦸‍♂️",
    "Send a random emoji to your best friend without context. 📲",
    "Give a motivational speech about how to win at life. 🎤",
    "Pretend to be a baby for the next 2 minutes. 👶",
    "Do an impression of a chicken for 1 minute. 🐔",
    "Call your mom and tell her you’ve joined a circus. 🎪",
    "Dance like you’re in a music video for 1 minute. 🎶",
    "Try to balance a spoon on your nose for 1 minute. 🥄",
    "Talk like a pirate for the next 2 minutes. 🏴‍☠️",
    "Do 10 squats while singing your favorite song. 🎶",
    "Pretend you’re a famous chef and give a recipe for a random dish. 🍳",
    "Try to walk in a straight line with your eyes closed. 🚶‍♂️",
    "Let someone else choose a random emoji to send to your best friend. 📲",
    "Imitate a cartoon character for the next 3 minutes. 🦸‍♂️",
    "Send a text to your crush saying ‘I think I just saw a UFO!’ 🛸",
    "Do your best dance move and let everyone vote on it. 💃",
    "Post a funny face on your story and ask people to guess what you’re doing. 🤪",
    "Do an impression of your favorite animal for 2 minutes. 🦁",
    "Sing the alphabet in a funny voice. 🎤",
    "Pretend to be a movie star for the next 2 minutes. 🎬",
    "Do 10 jumping jacks while singing ‘Happy Birthday’. 🎂",
    "Pretend to be a wizard and cast a spell for the next minute. 🧙‍♂️",
    "Post a random, funny photo to your story. 📸",
    "Dance in the middle of the room without any music for 1 minute. 🎶",
    "Make a funny face and hold it for 30 seconds. 🤪",
    "Pretend you’re an opera singer and sing a random song. 🎤",
    "Speak in a made-up language for the next 2 minutes. 🗣️",
    "Send a voice message singing your favorite song to your best friend. 🎶",
    "Pretend you’re a news reporter and give a funny news report. 📰",
    "Take a silly selfie and send it to your family group chat. 🤳",
    "Act like a monkey for 1 minute. 🐒",
    "Make up a dance routine and perform it for the group. 💃",
    "Send a random text to your friend and say, ‘I think I left my keys in the freezer.’ 🗝️",
    "Let someone send a funny voice message to your best friend. 📲",
    "Dance like you’re at a wedding for 1 minute. 💃",
    "Pretend you’re a robot and talk like one for 2 minutes. 🤖",
    "Post a video of yourself doing a dramatic reading of a text message. 📱",
    "Try to do a cartwheel without falling. 🤸‍♀️",
    "Pretend you’re a cat and crawl around the room. 🐱",
    "Send a text to your mom telling her you want to adopt a pet llama. 🦙",
    "Do an impression of your favorite celebrity. 🌟",
    "Take a video of yourself dancing and post it on your story. 🎶",
    "Pretend you’re a famous actor giving an acceptance speech for 1 minute. 🎬",
    "Talk in only rhymes for the next 5 minutes. 🎤",
    "Try to juggle 2 objects for 30 seconds. 🎲",
    "Send a voice message to your best friend singing ‘Twinkle Twinkle Little Star’. 🌟",
    "Imitate your favorite Disney character for 2 minutes. 🦸‍♂️",
    "Walk like a penguin for 1 minute. 🐧",
    "Do your best dance move to a song you don’t know. 🎶",
    "Pretend you’re a secret agent on a mission for the next 2 minutes. 🕵️‍♂️",
    "Do 20 jumping jacks while laughing. 😂",
    "Do an impression of someone famous for 1 minute. 🌟",
    "Pretend you’re a lifeguard and give instructions to everyone. 🏖️",
    "Do a dramatic reading of your most recent text message. 📱",
    "Send a funny voice memo to your best friend. 📲",
    "Pretend to be a dog and bark every time you speak. 🐶",
    "Do 10 sit-ups while singing your favorite song. 🎶",
    "Take a funny video of yourself and post it online. 📸",
    "Speak in a slow-motion voice for 1 minute. 🐢",
    "Dance to a random song without caring what anyone thinks. 🎶",
    "Act like a tree and freeze for 1 minute. 🌳",
    "Send a voice message telling your best friend you want to be a professional llama herder. 🦙",
    "Pretend to be a famous chef and explain how to cook a random dish. 🍳",
    "Try to do a handstand for 1 minute. 🤸‍♀️",
    "Do your best impersonation of a famous singer. 🎤",
    "Pretend to be a pirate and give instructions to everyone. 🏴‍☠️",
    "Walk around the room like a zombie for 1 minute. 🧟‍♀️",
    "Post a random picture with a caption, ‘Living my best life!’ 📸",
    "Send a text to a friend and say, ‘I’m pretty sure I saw a UFO today.’ 🛸",
    "Dance like you’re on a reality show for 1 minute. 💃",
    "Pretend to be an alien and talk about Earth for 1 minute. 👽",
    "Do 10 push-ups while singing a song. 🎶",
    "Do an impression of an animal until someone guesses what it is. 🦁",
    "Post a random song lyric and ask people to guess the song. 🎶",
    "Talk like a robot for the next 5 minutes. 🤖",
    "Do 10 squats while holding your breath. 💪",
    "Dance like you’re at a club for 1 minute. 🎶",
    "Do your best impression of a baby for 1 minute. 👶",
    "Try to touch your nose with your tongue. 👅",
    "Send a random voice message to your friend saying, ‘I’m pretty sure I’m a superhero.’ 🦸‍♂️",
    "Do 10 jumping jacks while humming a song. 🎶",
    "Pretend you’re an astronaut and describe your mission for 2 minutes. 🚀",
    "Send a funny emoji to your best friend without context. 📲",
    "Do 10 push-ups while pretending you’re a superhero. 🦸‍♀️",
    "Take a video of yourself doing a funny dance and post it online. 💃",
    "Pretend to be a fashion model and strike poses for 1 minute. 👗",
    "Send a random text to your mom saying, ‘I think I left my phone in the fridge.’ 📱",
    "Speak in only animal sounds for the next 5 minutes. 🐱",
    "Do your best impersonation of a cartoon character. 🦸‍♀️",
    "Walk like a crab for the next 2 minutes. 🦀",
    "Pretend you’re a famous chef and show everyone how to make a sandwich. 🍞",
    "Do your best dance move to a song of your choice. 🎶",
    "Pretend to be a superhero and perform a rescue mission for the group. 🦸‍♂️",
    "Try to juggle 3 random items for 1 minute. 🎲",
    "Make a funny sound every time you speak for the next 5 minutes. 🎤",
    "Dance like you’re at a wedding for 1 minute. 💃",
    "Imitate your favorite animal for 1 minute. 🦁",
    "Send a text to your best friend saying, ‘I’m pretty sure I saw a unicorn today.’ 🦄",
    
    # New dares from the provided list
    "Try doing a handstand for 1 minute 🤸",
    "Call your ex and give them a piece of your mind 📱",
    "Ask your neighbor for a penny 💰",
    "Pretend to be an elephant and send me a video 🐘",
    "Text someone random and say, 'I see ghosts' 👻",
    "Record yourself eating the spiciest thing in your house 🌶️",
    "Watch this weird video and send me your reaction 😅",
    "Post an embarrassing photo of yourself on Instagram Stories 📸",
    "Text someone a random joke 🤣",
    "Call Domino's and pretend to order Pizza Hut 📞",
    "Record yourself singing a song about butter 🎤",
    "Make me your lock screen for a week 😉",
    "Write me a love poem about my cat 📝",
    "Send me a screenshot of the first email in your inbox 📧",
    "Message someone you don't know that you're glad you're friends 💕",
    "Text your mom that you've been arrested 😱",
    "Post a hot photo of yourself on Instagram 🔥",
    "Shave your arms and send me a pic 💈",
    "Like your crush's first Instagram post 👍",
    "Kiss your phone like it's the love of your life 💏",
    "Text your dad that you're engaged 💍",
    "Try to lick your elbow 👅",
    "Take a shower with all your clothes on 🚿",
    "Send your 5th contact a random GIF 📱",
    "Open your window and sing as loud as you can 🎤",
    "Post a TikTok doing a silly dance 💃",
    "Walk around the block talking to yourself 🚶",
    "Brush your teeth with peanut butter and send me a pic 🥜",
    "Learn the first dance from your TikTok 'for you' page 💃",
    "Draw a beard on your face and take a selfie 📸",
    "Text the 10th guy in your contacts that he's cute 📱",
    "Text the 7th girl in your contacts that she's hot 😍",
    "Go to an open space and scream 😱",
    "Send a GIF to someone with no context 📱",
    "Eat a handful of dry noodles 🍜",
    "Eat an entire chocolate cake by yourself 🍰",
    "Send your dad the worst joke you've ever heard 🤣",
    "Text a friend, 'It's all your fault!' 😂",
    "Use an upside down text generator to message your mom 🙃",
    "Call your mom by her first name 📞",
    "Put your clothes on backwards and send me a pic 👚",
    "Put ice cream toppings on spaghetti and take a bite 🍨",
    "Set your alarm for 4 AM ⏰",
    "Confess your love for Donald Duck 🦆",
    "Send me a pic of your first crush 📸",
    "Eat a pickle dipped in peanut butter 🥒",
    "Eat a spoonful of mustard 🥄",
    "Wrap your head in toilet paper and say, 'I'm a mummy!' 🧻",
    "Change your profile picture to a baby picture of yourself 👶",
    "Send me the link of the last YouTube video you watched 🎥",
    "Tell me everything that's in your wallet/purse 👛",
    "Drink an entire jar of pickle juice 🥒",
    "Say something great about me in a Facebook update 💕",
    "Send a break-up text to someone random 💔",
    "Call a random number and keep them talking for 3 minutes 📞",
    "Take a video of yourself imitating a celebrity 🎬",
    "Send me a screenshot of your internet search history 🕵️",
    "Send me the 73rd photo in your phone 📸",
    "Send me your favorite meme 😂",
    "Crack an egg on your head 🥚",
    "Put ice cubes in your mouth and sing a song 🧊",
    "Lick your foot 👅",
    "Write a funny word on your forehead 🤪",
    "Order the first thing Doordash promotes to you 🍔",
    "Text your parents, 'I messed up' 😱",
    "Call me in your best British accent 🇬🇧",
    "Video call me and do your best dance 💃",
    "Put lipstick on with a blindfold on and send me a selfie 💄",
    "Call someone, shout 'Boo!' and then hang up 👻",
    "Stand in front of the mirror and say, 'I love you' 🥰",
    "Rub chocolate on your face and leave it there for 10 minutes 🍫",
    "Record yourself doing 2 minutes of freestyle rap 🎤"
]